version: "3.9"

services:
  db:
    image: postgres:16
    container_name: campusx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-campusx}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-campusx}
      POSTGRES_DB: ${POSTGRES_DB:-campusx}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: node:20
    working_dir: /app
    container_name: campusx-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-change-me}
      DATABASE_URL: postgres://${POSTGRES_USER:-campusx}:${POSTGRES_PASSWORD:-campusx}@db:5432/${POSTGRES_DB:-campusx}
      CORS_ORIGIN: http://localhost:5174
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"

  frontend:
    image: node:20
    working_dir: /app
    container_name: campusx-frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5174"

volumes:
  db_data: